name: Intermediate

on:

  workflow_call:

    inputs:

      # The consumer list (example: [c0, c1, c2]).
      consumers:
        required: true
        type: string

jobs:

  caller:

    # name: ${{ matrix.consumer }}

    # strategy:
    #   matrix:
    #     consumer: ${{ fromJSON(inputs.consumers) }}

    # uses: ./.github/workflows/leaf.yml

    # with:
    #   consumer: '${{ matrix.consumer }}'
    #   osList: '["ubuntu-22.04","ubuntu-20.04"]'

    name: ${{ matrix.consumer }}

    strategy:
      matrix:
        consumer: [c1,c2]
        
    uses: ./.github/workflows/leaf.yml

    with:
      consumer: ${{ matrix.consumer }}
      osList: '["ubuntu-22.04","ubuntu-20.04"]'

    # runs-on: ubuntu-latest

    # steps:

    #   - run: echo ${{ fromJSON(inputs.consumers) }}
