name: Intermediate

on:

  workflow_call:

    inputs:

      # The consumer list (example: [c0, c1, c2]).
      consumers:
        required: true
        type: array

jobs:

  caller:

    name: 

    strategy:
      matrix:
        consumer: ${{ inputs.consumers }}

    uses: ./.github/workflows/leaf.yml

    with:
      consumer: ${{ matrix.consumer }}
      osList: [ubuntu-22.04, ubuntu-20.04]
