name: Leaf

on:

  workflow_call:

    # inputs:

    #   # The consumer name.
    #   consumer:
    #     required: true
    #     type: string

    #   # The OS List (example: [ubuntu-22.04, ubuntu-20.04])
    #   osList:
    #     required: true
    #     type: string

  # workflow_dispatch:

  #   inputs:

  #     # The consumer name.
  #     consumer:
  #       required: true
  #       type: string

  #     # The OS List (example: [ubuntu-22.04, ubuntu-20.04])
  #     osList:
  #       required: true
  #       type: string


jobs:

  called:

    # name: ${{ inputs.consumer }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     os: ${{ fromJSON(inputs.osList) }}

    steps:

      - name: Print consumer & OS
        run: echo "foo"
        shell: bash
