name: Root

on:

  workflow_dispatch:

jobs:

  caller:

    name: ${{ matrix.name }}

    strategy:
      matrix: '{"include":[{"name":"batch0","consumers":"[\"c1\",\"c2\"]"},{"name":"batch1","consumers":"[\"c3\",\"c4\"]"}]}'

    uses: ./.github/workflows/intermediate.yml

    with:
      consumers: ${{ matrix.consumers }}
